version: "3"

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file: .env.development

        ports: 
            - '3000:3000'
        image: dev_app
        depends_on:
            - db

    
    db:
        image: postgres:14.1-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: jrs
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    db: