FROM node:20-alpine3.17 as build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn start-dev

FROM node:20-alpine3.17
WORKDIR /app
COPY --from=build /app/dist ./
COPY --from=build /app/package.json ./
RUN npm install --omit=dev
CMD ["node", "./index.js"]